version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vikshu_frontend
    ports:
      - "3007:3007"
    restart: unless-stopped
    networks:
      - vikshu_net

networks:
  vikshu_net:
    driver: bridge
